#=========== Users Section
### post user
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe",
    "phone":"1233",
    "password": "mysecret"
}


#============ Transcations section
### post user
POST http://localhost:8000/api/v1/transactions
Content-Type: application/json

{
    "title": "Salary"
}